---
format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone: {}
    - cache-pull: {}
    - script:
        title: Do anything with Script step
    - install-missing-android-tools: {}
    - gradle-runner:
        inputs:
        - gradle_file: "$GRADLE_BUILD_FILE_PATH"
        - gradle_task: assembleDebug testDebugUnitTestCoverage
        - gradlew_path: "$GRADLEW_PATH"
        title: Assemble and Test
    - cache-push: {}
    - deploy-to-bitrise-io:
        inputs:
        - deploy_path: "/bitrise/src/app/build/reports/"
        - is_compress: 'true'
        - notify_user_groups: none
        - zip_name: app_reports
        - notify_email_list: ''
        is_always_run: false
        title: Save App Reports
app:
  envs:
  - opts:
      is_expand: false
    GRADLE_BUILD_FILE_PATH: build.gradle
  - opts:
      is_expand: false
    GRADLEW_PATH: "./gradlew"
